ui:
  fontFamily: "Consolas"
  fontSize: 14
  defaultColor: "darkgray"
  startupMessage: "Welcome to our editor!"
  theme: "light"  
  wrapText: true

app:
  defaultDirectory: "C:/Users/Public/Documents"
  showTimeAndDate: true
  printDialog: true
