name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      # IMPORTANT: run from repo root (no working-directory: text-editor)
      - name: Build (package)
        run: mvn -B -q -DskipTests package

      - name: PMD (code quality)
        run: mvn -B -q pmd:pmd

      # Optional metrics step; won’t fail the job if missing
      - name: Metrics (CK) [optional]
        continue-on-error: true
        run: |
          mvn -q -DskipTests exec:java -Dexec.mainClass="com.texteditor.tools.MetricsRunner" \
          || echo "MetricsRunner not implemented; skipping."

      - name: Upload artifacts (JAR + reports)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/*.jar
            target/pmd.xml
            target/site/pmd.html
