name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build (package)
        run: mvn -B -DskipTests package

      - name: PMD (code quality)
        run: mvn -B pmd:pmd

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: text-editor-jar
          path: target/*.jar

      - name: Upload PMD report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pmd-report
          path: |
            target/pmd.xml
            target/site/pmd.html
